import{useEffect,useState}from'react';
const API=import.meta.env.VITE_API_URL??'http://localhost:4000';
export function FailoverPanel(){
 const[s,setS]=useState<any>(null),[enabled,setEnabled]=useState(false),[min,setMin]=useState(8),[hold,setHold]=useState(3),[cool,setCool]=useState(30),[msg,setMsg]=useState('');
 const load=async()=>{try{const r=await fetch(`${API}/api/failover/status`,{cache:'no-store'});const v=await r.json();setS(v);setEnabled(v.settings.enabled);setMin(v.settings.minimumImprovement);setHold(v.settings.holdCycles);setCool(v.settings.cooldownSeconds);setMsg('')}catch(e){setMsg(String(e))}};
 const save=async()=>{await fetch(`${API}/api/failover/settings`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,minimumImprovement:min,holdCycles:hold,cooldownSeconds:cool,emergencyPacketLoss:100})});setMsg('Autonomous failover settings saved.');load()};
 const evaluate=async()=>{await fetch(`${API}/api/failover/evaluate`,{method:'POST'});load()};
 const clear=async()=>{await fetch(`${API}/api/failover/history`,{method:'DELETE'});load()};
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 return <section className="card failover-card"><div className="card-header"><div><p className="section-label">AUTONOMOUS FAILOVER</p><h2>Automatic route recovery</h2></div><span className={`optimizer-live-badge ${enabled?'online':'offline'}`}>{enabled?'ARMED':'DISABLED'}</span></div><div className="failover-summary"><div><span>Current route</span><strong>{s?.currentAdapter??'Windows automatic'}</strong></div><div><span>Pending route</span><strong>{s?.pendingAdapter??'--'}</strong></div><div><span>Hold progress</span><strong>{s?.pendingCycles??0}/{hold}</strong></div><div><span>Cooldown</span><strong>{s?.cooldownRemainingSeconds??0}s</strong></div></div><div className="failover-controls"><label className="optimizer-switch"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>Enable autonomous failover</span></label><label>Minimum improvement<input type="number" min="0" max="100" value={min} onChange={e=>setMin(Number(e.target.value))}/></label><label>Confirmation cycles<input type="number" min="1" max="20" value={hold} onChange={e=>setHold(Number(e.target.value))}/></label><label>Cooldown seconds<input type="number" min="0" max="3600" value={cool} onChange={e=>setCool(Number(e.target.value))}/></label><button className="primary-button" onClick={save}>Save failover settings</button><button className="secondary-button" onClick={evaluate}>Evaluate now</button></div><p className="action-message">{msg||s?.lastDecision}</p><div className="failover-history-header"><h3>Route history</h3><button className="secondary-button" onClick={clear}>Clear history</button></div><div className="failover-history">{(s?.events??[]).slice(0,10).map((x:any)=><div className="failover-event" key={`${x.timestamp}-${x.newAdapter}`}><strong>{new Date(x.timestamp).toLocaleTimeString()}</strong><span>{x.previousAdapter??'Automatic'} â†’ {x.newAdapter}</span><span>{x.reason}</span></div>)}{!s?.events?.length&&<p className="empty-state">No automatic route changes recorded.</p>}</div></section>
}


