import{useEffect,useMemo,useState}from'react';
const API=import.meta.env.VITE_API_URL??'http://localhost:4000';
export function FleetPanel(){
 const[summary,setSummary]=useState<any>(null),[devices,setDevices]=useState<any[]>([]),[analytics,setAnalytics]=useState<any[]>([]),[alerts,setAlerts]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const latest=useMemo(()=>{const m=new Map<string,any>();for(const x of analytics){const p=m.get(x.deviceId);if(!p||new Date(x.createdAt)>new Date(p.createdAt))m.set(x.deviceId,x)}return m},[analytics]);
 const load=async()=>{try{setBusy(true);const[s,d,a,al]=await Promise.all([fetch(`${API}/api/fleet/summary`),fetch(`${API}/api/fleet/devices`),fetch(`${API}/api/fleet/analytics?limit=500`),fetch(`${API}/api/fleet/alerts`)]);for(const r of[s,d,a,al])if(!r.ok)throw new Error(await r.text());setSummary(await s.json());setDevices((await d.json()).devices??[]);setAnalytics((await a.json()).analytics??[]);setAlerts((await al.json()).alerts??[]);setMsg('')}catch(e){setMsg(String(e))}finally{setBusy(false)}};
 const command=async(deviceId:string,type:string)=>{try{setBusy(true);const r=await fetch(`${API}/api/fleet/commands`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId,type})});if(!r.ok)throw new Error(await r.text());const v=await r.json();setMsg(`Queued ${type}. Command ${v.id}`)}catch(e){setMsg(String(e))}finally{setBusy(false)}};
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 return <section className="card fleet-card"><div className="card-header"><div><p className="section-label">NNIT FLEET CLOUD</p><h2>Enterprise device management</h2></div><span className="optimizer-live-badge online">{summary?.onlineDevices??0} ONLINE</span></div>
 <div className="fleet-summary"><div><span>Devices</span><strong>{summary?.devices??'--'}</strong></div><div><span>Online</span><strong>{summary?.onlineDevices??'--'}</strong></div><div><span>Alerts</span><strong>{summary?.activeAlerts??'--'}</strong></div><div><span>Samples</span><strong>{summary?.analyticsSamples??'--'}</strong></div><div><span>Queued</span><strong>{summary?.queuedCommands??'--'}</strong></div></div>
 <div className="fleet-grid">{devices.map((d:any)=>{const x=latest.get(d.id);const ac=alerts.filter((a:any)=>a.deviceId===d.id&&!a.resolved).length;return <article className="fleet-device" key={d.id}><div className="fleet-device-header"><div><strong>{d.name}</strong><span>{d.platform} · agent {d.agentVersion}</span></div><span className={`cloud-device-state ${d.online?'online':'offline'}`}>{d.online?'ONLINE':'OFFLINE'}</span></div><div className="fleet-stats"><div><span>Score</span><strong>{x?.score??d.metadata?.score??'--'}</strong></div><div><span>Latency</span><strong>{x?.latencyMs??d.metadata?.latencyMs??'--'} ms</strong></div><div><span>DNS</span><strong>{x?.dnsLatencyMs??d.metadata?.dnsLatencyMs??'--'} ms</strong></div><div><span>Jitter</span><strong>{x?.jitterMs??'--'} ms</strong></div><div><span>Loss</span><strong>{x?.packetLoss??d.metadata?.packetLoss??'--'}%</strong></div><div><span>Alerts</span><strong>{ac}</strong></div></div><div className="fleet-device-meta"><span>Device ID: {d.id}</span><span>Last seen: {d.lastSeenAt?new Date(d.lastSeenAt).toLocaleString():'--'}</span></div><div className="fleet-actions"><button className="secondary-button" disabled={busy} onClick={()=>command(d.id,'ping-agent')}>Ping agent</button><button className="secondary-button" disabled={busy} onClick={()=>command(d.id,'send-telemetry')}>Request telemetry</button></div></article>})}</div><p className="action-message">{msg}</p><p className="traffic-note">Railway credentials remain in the local NNIT API. Browser requests go only to localhost. Remote commands remain whitelist-only. Resource pressure alerts sync automatically to the cloud.</p></section>
}





